# Python version
ARG PYTHON_VERSION=3.10.11

# ------------------------------------------------------BACKEND

FROM python:${PYTHON_VERSION} as backend

LABEL maintainer="2023 MyHomeworks, { }"

ENV PYTHONUNBUFFERED=1

ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app/API

RUN python3 -m venv venv && . venv/bin/activate && pip install --upgrade pip

COPY ./API/requirements.txt .

RUN pip install -r requirements.txt

COPY ./API .

WORKDIR /app

COPY ./.env .

WORKDIR /app/API