# Generated by Django 5.0.2 on 2024-02-14 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="",
                        help_text="Tutorial title",
                        max_length=100,
                        unique=True,
                        verbose_name="Tutorial title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="",
                        help_text="Tutorial description",
                        max_length=1000,
                        verbose_name="Tutorial description",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Tutorial published",
                        verbose_name="Tutorial published",
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        default=datetime.datetime.now,
                        help_text="Tutorial publish date",
                        verbose_name="Tutorial publish date",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial",
                "verbose_name_plural": "Tutorials",
                "ordering": ["publish_date"],
            },
        ),
    ]
