# Generated by Django 5.0.2 on 2024-02-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Tutorials__main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='publish_date',
            field=models.DateTimeField(default='', help_text='Tutorial publish date', verbose_name='Tutorial publish date'),
        ),
    ]
