# Generated by Django 5.0.2 on 2024-02-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Tutorials__main', '0002_alter_tutorial_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='publish_date',
            field=models.DateField(default='', help_text='Tutorial publish date', verbose_name='Tutorial publish date'),
        ),
    ]
