# Generated by Django 5.0.2 on 2024-02-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Tutorials__main', '0007_alter_tutorial_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='publish_date',
            field=models.DateField(blank=True, default='', help_text='Tutorial publish date in format YYYY-MM-DD', null=True, verbose_name='Tutorial publish date'),
        ),
    ]
