# Generated by Django 5.1.4 on 2024-12-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorials__main', '0003_alter_tutorial_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='id',
            field=models.UUIDField(editable=False, help_text='Tutorial ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(editable=False, help_text='User ID', primary_key=True, serialize=False),
        ),
    ]
