# Generated by Django 5.1.4 on 2025-02-17 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tutorials__main", "0007_alter_tutorial_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created the tutorial",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User who created the tutorial",
            ),
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Tutorial description",
                max_length=1000,
                null=True,
                verbose_name="Tutorial description",
            ),
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="published_at",
            field=models.DateTimeField(
                help_text="Date and time when the tutorial was published",
                null=True,
                verbose_name="Date and time when the tutorial was published",
            ),
        ),
    ]
